# Generated by Django 5.1.1 on 2024-09-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(max_length=100)),
                ('projector_qty', models.CharField(max_length=100)),
                ('led_qty', models.CharField(max_length=5)),
                ('monitor_qty', models.CharField(max_length=5)),
                ('keyboard_qty', models.CharField(max_length=5)),
                ('mouse_qty', models.CharField(max_length=5)),
                ('cpu_qty', models.CharField(max_length=5)),
                ('ups_qty', models.CharField(max_length=5)),
                ('sub_cord_qty', models.CharField(max_length=5)),
                ('power_cord_qty', models.CharField(max_length=5)),
                ('total_qty', models.CharField(max_length=5)),
                ('other_qty', models.CharField(max_length=20)),
            ],
        ),
    ]
