# Generated by Django 4.2.16 on 2024-10-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('projector_qty', models.PositiveIntegerField(default=0)),
                ('led_qty', models.PositiveIntegerField(default=0)),
                ('monitor_qty', models.PositiveIntegerField(default=0)),
                ('keyboard_qty', models.PositiveIntegerField(default=0)),
                ('mouse_qty', models.PositiveIntegerField(default=0)),
                ('cpu_qty', models.PositiveIntegerField(default=0)),
                ('ups_qty', models.PositiveIntegerField(default=0)),
                ('sub_cord_qty', models.PositiveIntegerField(default=0)),
                ('power_cord_qty', models.PositiveIntegerField(default=0)),
                ('is_returned', models.BooleanField(default=False)),
            ],
        ),
    ]
