# Generated by Django 4.2.16 on 2024-11-08 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrower_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReturnedItem',
            new_name='ReturnedInfo',
        ),
    ]
