# Generated by Django 4.2.16 on 2024-10-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='borrowerinfo',
            name='is_returned',
        ),
        migrations.AlterField(
            model_name='borrowerinfo',
            name='cpu_qty',
            field=models.IntegerField(verbose_name=5),
        ),
        migrations.AlterField(
            model_name='borrowerinfo',
            name='keyboard_qty',
            field=models.IntegerField(verbose_name=5),
        ),
        migrations.AlterField(
            model_name='borrowerinfo',
            name='led_qty',
            field=models.IntegerField(verbose_name=5),
        ),
        migrations.AlterField(
            model_name='borrowerinfo',
            name='middle_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='borrowerinfo',
            name='monitor_qty',
            field=models.IntegerField(verbose_name=5),
        ),
        migrations.AlterField(
            model_name='borrowerinfo',
            name='mouse_qty',
            field=models.IntegerField(verbose_name=5),
        ),
        migrations.AlterField(
            model_name='borrowerinfo',
            name='power_cord_qty',
            field=models.IntegerField(verbose_name=5),
        ),
        migrations.AlterField(
            model_name='borrowerinfo',
            name='projector_qty',
            field=models.IntegerField(verbose_name=5),
        ),
        migrations.AlterField(
            model_name='borrowerinfo',
            name='sub_cord_qty',
            field=models.IntegerField(verbose_name=5),
        ),
        migrations.AlterField(
            model_name='borrowerinfo',
            name='ups_qty',
            field=models.IntegerField(verbose_name=5),
        ),
    ]
