# Generated by Django 5.1.1 on 2024-10-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower_app', '0002_alter_borrowerinfo_cpu_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowerinfo',
            name='cpu_qty',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='borrowerinfo',
            name='keyboard_qty',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='borrowerinfo',
            name='led_qty',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='borrowerinfo',
            name='monitor_qty',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='borrowerinfo',
            name='mouse_qty',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='borrowerinfo',
            name='power_cord_qty',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='borrowerinfo',
            name='projector_qty',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='borrowerinfo',
            name='sub_cord_qty',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='borrowerinfo',
            name='ups_qty',
            field=models.IntegerField(max_length=5),
        ),
    ]
